import io
import datetime
from typing import Dict, Any, Optional, Tuple, List
import pandas as pd
from werkzeug.utils import secure_filename

# OpenPyXL for Excel export
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ReportLab for PDF export
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether, HRFlowable
)
from reportlab.pdfgen import canvas

# Import existing services and report generators (Single Source of Truth)
from services.dataset_manager import DatasetManager
from services.report_cache_service import ReportCacheService
from services.dashboard_service import (
    get_highest_severity,
    calculate_health_score,
    get_dataset_status
)
from services.quality_service import (
    generate_business_impact,
    generate_recommendation
)
from reports.overview import generate_overview_report
from reports.missing import generate_missing_report
from reports.duplicate import generate_duplicate_report
from reports.datatype import generate_datatype_report
from reports.outlier import generate_outlier_report
from reports.dashboard import generate_dashboard_report


# ==========================================
# Numbered Canvas for Running PDF Header/Footer
# ==========================================

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to calculate and render dynamic total page numbers ("Page X of Y"),
    along with running header and footer banners.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Running Header (on all pages)
        self.drawString(36, 756, "DataLens Enterprise Data Quality Audit")
        self.drawRightString(letter[0] - 36, 756, datetime.datetime.now().strftime("%Y-%m-%d %H:%M"))
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.75)
        self.line(36, 750, letter[0] - 36, 750)

        # Running Footer
        self.line(36, 42, letter[0] - 36, 42)
        self.drawString(36, 30, "CONFIDENTIAL — Generated by DataLens Automated Quality Suite")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(letter[0] - 36, 30, page_str)
        self.restoreState()


class ReportExportService:
    """
    Export service that collects existing analysis results from ReportCacheService / DatasetManager
    and formats them into downloadable PDF and Excel reports.
    """

    @classmethod
    def get_all_reports_data(cls, filename: Optional[str] = None) -> Tuple[Optional[Dict[str, Any]], Optional[str]]:
        """
        Gathers all 6 reports for a dataset.
        Reuses cached reports from ReportCacheService. If any report is not yet cached,
        it generates it using the existing report generator functions and stores it in ReportCacheService.
        """
        df, err = DatasetManager.get_dataframe(filename)
        if err or df is None:
            return None, err or "No active dataset loaded."

        clean_filename = secure_filename(filename) if filename else (DatasetManager.get_active_filename() or "dataset.csv")

        # 1. Overview Report
        overview_payload = ReportCacheService.get_report("overview", clean_filename)
        if overview_payload is None:
            overview_df = generate_overview_report(df)
            missing_df = generate_missing_report(df)
            dup_df, _ = generate_duplicate_report(df)
            dtype_df = generate_datatype_report(df)
            outlier_df = generate_outlier_report(df)

            health_res = calculate_health_score(missing_df, dup_df, dtype_df, outlier_df)
            health_score = health_res["Health Score"]
            health_rating = get_dataset_status(health_score)
            metrics = dict(zip(overview_df["Metric"], overview_df["Value"]))

            overview_payload = {
                "dataset_name": clean_filename,
                "total_rows": int(metrics.get("Rows", len(df))),
                "total_columns": int(metrics.get("Columns", len(df.columns))),
                "memory_usage_mb": float(metrics.get("Memory Usage (MB)", 0.0)),
                "numeric_columns": int(metrics.get("Numeric Columns", 0)),
                "categorical_columns": int(metrics.get("Categorical Columns", 0)),
                "total_missing_values": int(metrics.get("Missing Values", 0)),
                "total_duplicate_records": int(metrics.get("Duplicate Rows", 0)),
                "health_score": health_score,
                "health_rating": health_rating,
                "analyzed_at": "Just now"
            }
            ReportCacheService.set_report("overview", overview_payload, clean_filename)

        # 2. Missing Values Report
        missing_payload = ReportCacheService.get_report("missing", clean_filename)
        if missing_payload is None:
            missing_df = generate_missing_report(df)
            total_missing = int(missing_df["Missing Count"].sum()) if not missing_df.empty else 0
            pct_missing_rows = round(float(df.isnull().any(axis=1).sum() / len(df)) * 100, 2) if len(df) > 0 else 0.0
            overall_severity = get_highest_severity(missing_df) if not missing_df.empty else "No Issue"
            business_impact = generate_business_impact("missing", overall_severity)
            recommendation = generate_recommendation("missing", overall_severity)

            columns = []
            for _, row in missing_df.iterrows():
                col_name = str(row["Column"])
                columns.append({
                    "column_name": col_name,
                    "missing_count": int(row["Missing Count"]),
                    "missing_pct": float(row["Missing Percentage"]),
                    "datatype": str(df[col_name].dtype) if col_name in df.columns else "unknown",
                    "severity": str(row["Severity"])
                })

            missing_payload = {
                "total_missing_values": total_missing,
                "percentage_missing_rows": pct_missing_rows,
                "overall_severity": overall_severity,
                "business_impact": business_impact,
                "recommendation": recommendation,
                "columns": columns
            }
            ReportCacheService.set_report("missing", missing_payload, clean_filename)

        # 3. Duplicate Records Report
        duplicate_payload = ReportCacheService.get_report("duplicate", clean_filename)
        if duplicate_payload is None:
            summary_df, duplicate_records = generate_duplicate_report(df)
            total_duplicates = int(summary_df["Duplicate Records"].iloc[0]) if not summary_df.empty else 0
            pct_duplicates = float(summary_df["Duplicate Percentage"].iloc[0]) if not summary_df.empty else 0.0
            overall_severity = str(summary_df["Severity"].iloc[0]) if not summary_df.empty else "No Issue"
            business_impact = str(summary_df["Business Impact"].iloc[0]) if not summary_df.empty else "No duplicate issue."
            recommendation = str(summary_df["Recommendation"].iloc[0]) if not summary_df.empty else "No action required."

            samples = []
            if not duplicate_records.empty:
                raw_samples = duplicate_records.head(20).to_dict(orient="records")
                for record in raw_samples:
                    clean_record = {str(k): (None if pd.isna(v) else v) for k, v in record.items()}
                    clean_record["duplicate_count"] = 2
                    samples.append(clean_record)

            duplicate_payload = {
                "total_duplicate_rows": total_duplicates,
                "percentage_duplicates": pct_duplicates,
                "overall_severity": overall_severity,
                "business_impact": business_impact,
                "recommendation": recommendation,
                "duplicate_samples": samples
            }
            ReportCacheService.set_report("duplicate", duplicate_payload, clean_filename)

        # 4. Datatype Validation Report
        datatype_payload = ReportCacheService.get_report("datatype", clean_filename)
        if datatype_payload is None:
            datatype_df = generate_datatype_report(df)
            total_invalid = int(datatype_df["Invalid Values"].sum()) if not datatype_df.empty else 0
            overall_severity = get_highest_severity(datatype_df) if not datatype_df.empty else "No Issue"
            business_impact = generate_business_impact("datatype", overall_severity)
            recommendation = generate_recommendation("datatype", overall_severity)

            issues = []
            for _, row in datatype_df.iterrows():
                invalid_cnt = int(row["Invalid Values"])
                issues.append({
                    "column_name": str(row["Column"]),
                    "expected_type": str(row["Expected Datatype"]),
                    "detected_type": str(row["Detected Datatype"]),
                    "invalid_count": invalid_cnt,
                    "severity": str(row["Severity"]),
                    "issue_description": f"Found {invalid_cnt} values inconsistent with expected type '{row['Expected Datatype']}'."
                })

            datatype_payload = {
                "total_invalid_types": total_invalid,
                "columns_analyzed": len(df.columns),
                "overall_severity": overall_severity,
                "business_impact": business_impact,
                "recommendation": recommendation,
                "issues": issues
            }
            ReportCacheService.set_report("datatype", datatype_payload, clean_filename)

        # 5. Outlier Detection Report
        outlier_payload = ReportCacheService.get_report("outlier", clean_filename)
        if outlier_payload is None:
            outlier_df = generate_outlier_report(df)
            total_outliers = int(outlier_df["Outlier Count"].sum()) if not outlier_df.empty else 0
            overall_severity = get_highest_severity(outlier_df) if not outlier_df.empty else "No Issue"
            business_impact = generate_business_impact("outlier", overall_severity)
            recommendation = generate_recommendation("outlier", overall_severity)

            num_cols = df.select_dtypes(include=["number"]).columns
            summary = []
            for _, row in outlier_df.iterrows():
                col_name = str(row["Column"])
                series = df[col_name].dropna() if col_name in df.columns else pd.Series(dtype=float)
                summary.append({
                    "column_name": col_name,
                    "outlier_count": int(row["Outlier Count"]),
                    "percentage": float(row["Outlier Percentage"]),
                    "lower_bound": float(row["Lower Bound"]),
                    "upper_bound": float(row["Upper Bound"]),
                    "min_val": round(float(series.min()), 2) if not series.empty else 0,
                    "max_val": round(float(series.max()), 2) if not series.empty else 0,
                    "severity": str(row["Severity"])
                })

            outlier_payload = {
                "total_outliers": total_outliers,
                "columns_analyzed": len(num_cols),
                "overall_severity": overall_severity,
                "business_impact": business_impact,
                "recommendation": recommendation,
                "summary": summary
            }
            ReportCacheService.set_report("outlier", outlier_payload, clean_filename)

        # 6. Dashboard Report
        dashboard_payload = ReportCacheService.get_report("dashboard", clean_filename)
        if dashboard_payload is None:
            missing_df = generate_missing_report(df)
            dup_df, _ = generate_duplicate_report(df)
            dtype_df = generate_datatype_report(df)
            outlier_df = generate_outlier_report(df)

            dash_report = generate_dashboard_report(missing_df, dup_df, dtype_df, outlier_df)
            dash_summary_df = dash_report["dashboard_summary"]
            score_breakdown = dash_report["score_breakdown"]
            metrics = dict(zip(dash_summary_df["Metric"], dash_summary_df["Value"]))

            health_score = int(metrics.get("Health Score", 100))
            status = str(metrics.get("Dataset Status", "Unknown"))
            highest_priority = str(metrics.get("Highest Priority Issue", "None"))

            total_missing = int(missing_df["Missing Count"].sum()) if not missing_df.empty else 0
            total_dups = int(dup_df["Duplicate Records"].iloc[0]) if not dup_df.empty else 0
            total_invalid = int(dtype_df["Invalid Values"].sum()) if not dtype_df.empty else 0
            total_outliers = int(outlier_df["Outlier Count"].sum()) if not outlier_df.empty else 0
            total_issues = total_missing + total_dups + total_invalid + total_outliers

            critical_issues = 0
            high_issues = 0
            for rep in [missing_df, dtype_df, outlier_df]:
                if not rep.empty and "Severity" in rep.columns:
                    critical_issues += int((rep["Severity"] == "Critical").sum())
                    high_issues += int((rep["Severity"] == "High").sum())

            quick_insights = [
                f"Dataset health score is {health_score}/100 ({status}). Highest priority issue: {highest_priority}.",
                f"Total missing values identified across attributes: {total_missing}.",
                f"Total duplicate records detected in dataset: {total_dups}.",
                f"Schema type mismatches: {total_invalid}, statistical outliers: {total_outliers}."
            ]

            dashboard_payload = {
                "summary": {
                    "health_score": health_score,
                    "status": status,
                    "highest_priority": highest_priority,
                    "total_issues": total_issues,
                    "critical_issues": critical_issues,
                    "high_issues": high_issues
                },
                "score_breakdown": score_breakdown,
                "quick_insights": quick_insights
            }
            ReportCacheService.set_report("dashboard", dashboard_payload, clean_filename)

        full_data = {
            "filename": clean_filename,
            "generated_at": datetime.datetime.now().strftime("%B %d, %Y - %I:%M %p"),
            "overview": overview_payload,
            "missing": missing_payload,
            "duplicate": duplicate_payload,
            "datatype": datatype_payload,
            "outlier": outlier_payload,
            "dashboard": dashboard_payload
        }

        return full_data, None

    # ==========================================
    # PDF REPORT GENERATION (ReportLab)
    # ==========================================

    @classmethod
    def generate_pdf(cls, filename: Optional[str] = None) -> Tuple[Optional[io.BytesIO], Optional[str]]:
        """
        Transforms cached DataLens report data into a professional PDF document.
        """
        data, err = cls.get_all_reports_data(filename)
        if err or data is None:
            return None, err or "Failed to retrieve analysis data."

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()
        
        # Color palette
        c_primary = colors.HexColor("#1E3A8A")   # Navy
        c_brand = colors.HexColor("#2563EB")     # Blue
        c_dark = colors.HexColor("#0F172A")      # Slate Dark
        c_muted = colors.HexColor("#475569")     # Slate Muted
        c_bg_subtle = colors.HexColor("#F8FAFC") # Light surface
        c_border = colors.HexColor("#CBD5E1")    # Border gray

        # Severity Colors
        sev_colors = {
            "Critical": colors.HexColor("#DC2626"),
            "High": colors.HexColor("#EA580C"),
            "Medium": colors.HexColor("#D97706"),
            "Low": colors.HexColor("#2563EB"),
            "No Issue": colors.HexColor("#16A34A")
        }

        # Typography Styles
        style_title = ParagraphStyle(
            'DL_Title',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            textColor=c_dark
        )
        style_subtitle = ParagraphStyle(
            'DL_Subtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=c_muted
        )
        style_h1 = ParagraphStyle(
            'DL_H1',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=13,
            leading=17,
            textColor=c_primary,
            spaceBefore=12,
            spaceAfter=6
        )
        style_body = ParagraphStyle(
            'DL_Body',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=13,
            textColor=c_dark
        )
        style_muted = ParagraphStyle(
            'DL_Muted',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8.5,
            leading=12,
            textColor=c_muted
        )
        style_th = ParagraphStyle(
            'DL_TH',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8.5,
            leading=11,
            textColor=colors.white,
            alignment=0
        )
        style_td = ParagraphStyle(
            'DL_TD',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8,
            leading=11,
            textColor=c_dark
        )
        style_td_bold = ParagraphStyle(
            'DL_TD_Bold',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8,
            leading=11,
            textColor=c_dark
        )

        printable_w = letter[0] - 72  # 540 pt

        story = []

        # --- Header & Banner ---
        banner_data = [
            [
                Paragraph("<b>DataLens</b> Enterprise Data Quality Audit", style_title),
                Paragraph(f"<b>Dataset:</b> {data['filename']}<br/><b>Generated:</b> {data['generated_at']}", style_subtitle)
            ]
        ]
        t_banner = Table(banner_data, colWidths=[320, 220])
        t_banner.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('ALIGN', (1,0), (1,0), 'RIGHT'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(t_banner)
        story.append(HRFlowable(width="100%", thickness=1.5, color=c_brand, spaceBefore=4, spaceAfter=10))

        # --- Section 1: Executive Summary & Health Score ---
        dash = data["dashboard"]["summary"]
        dash_breakdown = data["dashboard"]["score_breakdown"]
        overview = data["overview"]

        score_color = colors.HexColor("#16A34A") if dash["health_score"] >= 75 else (colors.HexColor("#D97706") if dash["health_score"] >= 60 else colors.HexColor("#DC2626"))

        exec_summary_table = [
            [
                Paragraph(f"<font size=24 color='{score_color.hexval()}'><b>{dash['health_score']} / 100</b></font><br/><b>Status:</b> {dash['status']}", style_body),
                Paragraph(f"<b>Total Anomalies:</b> {dash['total_issues']:,}<br/>"
                          f"<b>Critical Defects:</b> {dash['critical_issues']:,} &nbsp;|&nbsp; <b>High Defects:</b> {dash['high_issues']:,}<br/>"
                          f"<b>Priority Focus:</b> <font color='#DC2626'><b>{dash['highest_priority']}</b></font>", style_body),
                Paragraph(f"<b>Missing:</b> -{dash_breakdown.get('Missing', 0)} pts<br/>"
                          f"<b>Duplicate:</b> -{dash_breakdown.get('Duplicate', 0)} pts<br/>"
                          f"<b>Datatype:</b> -{dash_breakdown.get('Datatype', 0)} pts<br/>"
                          f"<b>Outlier:</b> -{dash_breakdown.get('Outlier', 0)} pts", style_body)
            ]
        ]
        t_exec = Table(exec_summary_table, colWidths=[140, 230, 170])
        t_exec.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), c_bg_subtle),
            ('BOX', (0,0), (-1,-1), 1, c_border),
            ('INNERGRID', (0,0), (-1,-1), 0.5, c_border),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('LEFTPADDING', (0,0), (-1,-1), 10),
            ('RIGHTPADDING', (0,0), (-1,-1), 10),
        ]))
        story.append(Paragraph("1. Executive Summary & Quality Health Score", style_h1))
        story.append(t_exec)
        story.append(Spacer(1, 8))

        # Executive Insights
        if data["dashboard"]["quick_insights"]:
            insights_html = "".join([f"• {item}<br/>" for item in data["dashboard"]["quick_insights"]])
            story.append(Paragraph(f"<b>Executive Key Findings:</b><br/>{insights_html}", style_muted))
            story.append(Spacer(1, 10))

        # --- Section 2: Dataset Overview ---
        story.append(Paragraph("2. Dataset Structural Overview", style_h1))
        overview_table = [
            [
                Paragraph("<b>Metric</b>", style_th),
                Paragraph("<b>Value</b>", style_th),
                Paragraph("<b>Metric</b>", style_th),
                Paragraph("<b>Value</b>", style_th)
            ],
            [
                Paragraph("Total Records (Rows)", style_td),
                Paragraph(f"{overview['total_rows']:,}", style_td_bold),
                Paragraph("Total Attributes (Columns)", style_td),
                Paragraph(f"{overview['total_columns']:,}", style_td_bold)
            ],
            [
                Paragraph("Numeric Columns", style_td),
                Paragraph(f"{overview['numeric_columns']}", style_td),
                Paragraph("Categorical Columns", style_td),
                Paragraph(f"{overview['categorical_columns']}", style_td)
            ],
            [
                Paragraph("Missing Values Count", style_td),
                Paragraph(f"{overview['total_missing_values']:,}", style_td_bold),
                Paragraph("Duplicate Rows Count", style_td),
                Paragraph(f"{overview['total_duplicate_records']:,}", style_td_bold)
            ],
            [
                Paragraph("Memory Footprint", style_td),
                Paragraph(f"{overview['memory_usage_mb']} MB", style_td),
                Paragraph("Dataset Health Rating", style_td),
                Paragraph(f"{overview['health_rating']}", style_td_bold)
            ]
        ]
        t_overview = Table(overview_table, colWidths=[140, 130, 140, 130])
        t_overview.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), c_primary),
            ('GRID', (0,0), (-1,-1), 0.5, c_border),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_bg_subtle]),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(t_overview)
        story.append(Spacer(1, 12))

        # Helper for severity pill cell
        def make_sev_p_cell(severity_str):
            color = sev_colors.get(severity_str, colors.HexColor("#64748B"))
            return Paragraph(f"<font color='{color.hexval()}'><b>{severity_str}</b></font>", style_td)

        # --- Section 3: Missing Value Analysis ---
        missing = data["missing"]
        story.append(Paragraph("3. Missing Values Investigation", style_h1))
        story.append(Paragraph(
            f"<b>Total Missing Values:</b> {missing['total_missing_values']:,} &nbsp;|&nbsp; "
            f"<b>Rows with Missing Data:</b> {missing['percentage_missing_rows']}% &nbsp;|&nbsp; "
            f"<b>Overall Severity:</b> <font color='{sev_colors.get(missing['overall_severity'], c_dark).hexval()}'><b>{missing['overall_severity']}</b></font><br/>"
            f"<b>Business Impact:</b> {missing['business_impact']}<br/>"
            f"<b>Prescribed Action:</b> {missing['recommendation']}",
            style_body
        ))
        story.append(Spacer(1, 6))

        missing_table_data = [
            [
                Paragraph("<b>Column Name</b>", style_th),
                Paragraph("<b>Datatype</b>", style_th),
                Paragraph("<b>Missing Count</b>", style_th),
                Paragraph("<b>Missing %</b>", style_th),
                Paragraph("<b>Severity</b>", style_th)
            ]
        ]
        for col in missing.get("columns", []):
            missing_table_data.append([
                Paragraph(str(col.get("column_name", "")), style_td_bold),
                Paragraph(str(col.get("datatype", "")), style_td),
                Paragraph(f"{col.get('missing_count', 0):,}", style_td),
                Paragraph(f"{col.get('missing_pct', 0):.2f}%", style_td),
                make_sev_p_cell(col.get("severity", "No Issue"))
            ])

        t_missing = Table(missing_table_data, colWidths=[160, 90, 100, 90, 100])
        t_missing.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), c_primary),
            ('GRID', (0,0), (-1,-1), 0.5, c_border),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_bg_subtle]),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(t_missing)
        story.append(Spacer(1, 12))

        # --- Section 4: Duplicate Records Analysis ---
        dup = data["duplicate"]
        story.append(Paragraph("4. Duplicate Records Investigation", style_h1))
        story.append(Paragraph(
            f"<b>Duplicate Rows:</b> {dup['total_duplicate_rows']:,} &nbsp;|&nbsp; "
            f"<b>Duplicate Rate:</b> {dup['percentage_duplicates']}% &nbsp;|&nbsp; "
            f"<b>Overall Severity:</b> <font color='{sev_colors.get(dup['overall_severity'], c_dark).hexval()}'><b>{dup['overall_severity']}</b></font><br/>"
            f"<b>Business Impact:</b> {dup['business_impact']}<br/>"
            f"<b>Prescribed Action:</b> {dup['recommendation']}",
            style_body
        ))
        story.append(Spacer(1, 6))

        samples = dup.get("duplicate_samples", [])
        if samples:
            sample_keys = [k for k in samples[0].keys() if k != "duplicate_count"][:5]
            dup_cols_w = [printable_w / (len(sample_keys) + 1)] * (len(sample_keys) + 1)
            dup_table_data = [
                [Paragraph(f"<b>{k}</b>", style_th) for k in sample_keys] + [Paragraph("<b>Duplicates</b>", style_th)]
            ]
            for row in samples[:5]:
                dup_table_data.append(
                    [Paragraph(str(row.get(k, "")), style_td) for k in sample_keys] +
                    [Paragraph(f"{row.get('duplicate_count', 2)} copies", style_td_bold)]
                )
            t_dup = Table(dup_table_data, colWidths=dup_cols_w)
            t_dup.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), c_primary),
                ('GRID', (0,0), (-1,-1), 0.5, c_border),
                ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_bg_subtle]),
                ('TOPPADDING', (0,0), (-1,-1), 3),
                ('BOTTOMPADDING', (0,0), (-1,-1), 3),
                ('LEFTPADDING', (0,0), (-1,-1), 5),
                ('RIGHTPADDING', (0,0), (-1,-1), 5),
            ]))
            story.append(t_dup)
        else:
            story.append(Paragraph("<i>✓ Clean: No duplicate records detected in the active dataset.</i>", style_muted))
        story.append(Spacer(1, 12))

        # --- Section 5: Datatype Validation ---
        dtype = data["datatype"]
        story.append(Paragraph("5. Datatype Conformance & Schema Validation", style_h1))
        story.append(Paragraph(
            f"<b>Invalid Type Mismatches:</b> {dtype['total_invalid_types']:,} &nbsp;|&nbsp; "
            f"<b>Columns Validated:</b> {dtype['columns_analyzed']} &nbsp;|&nbsp; "
            f"<b>Overall Severity:</b> <font color='{sev_colors.get(dtype['overall_severity'], c_dark).hexval()}'><b>{dtype['overall_severity']}</b></font><br/>"
            f"<b>Business Impact:</b> {dtype['business_impact']}<br/>"
            f"<b>Prescribed Action:</b> {dtype['recommendation']}",
            style_body
        ))
        story.append(Spacer(1, 6))

        dtype_table_data = [
            [
                Paragraph("<b>Column Name</b>", style_th),
                Paragraph("<b>Detected Type</b>", style_th),
                Paragraph("<b>Expected Type</b>", style_th),
                Paragraph("<b>Invalid Values</b>", style_th),
                Paragraph("<b>Severity</b>", style_th)
            ]
        ]
        for issue in dtype.get("issues", []):
            dtype_table_data.append([
                Paragraph(str(issue.get("column_name", "")), style_td_bold),
                Paragraph(str(issue.get("detected_type", "")), style_td),
                Paragraph(str(issue.get("expected_type", "")), style_td),
                Paragraph(f"{issue.get('invalid_count', 0):,}", style_td),
                make_sev_p_cell(issue.get("severity", "No Issue"))
            ])

        t_dtype = Table(dtype_table_data, colWidths=[140, 100, 100, 100, 100])
        t_dtype.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), c_primary),
            ('GRID', (0,0), (-1,-1), 0.5, c_border),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_bg_subtle]),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(t_dtype)
        story.append(Spacer(1, 12))

        # --- Section 6: Outlier Detection ---
        outlier = data["outlier"]
        story.append(Paragraph("6. Statistical Outlier Detection", style_h1))
        story.append(Paragraph(
            f"<b>Total Anomalies:</b> {outlier['total_outliers']:,} &nbsp;|&nbsp; "
            f"<b>Numeric Features:</b> {outlier['columns_analyzed']} &nbsp;|&nbsp; "
            f"<b>Overall Severity:</b> <font color='{sev_colors.get(outlier['overall_severity'], c_dark).hexval()}'><b>{outlier['overall_severity']}</b></font><br/>"
            f"<b>Business Impact:</b> {outlier['business_impact']}<br/>"
            f"<b>Prescribed Action:</b> {outlier['recommendation']}",
            style_body
        ))
        story.append(Spacer(1, 6))

        outlier_table_data = [
            [
                Paragraph("<b>Column</b>", style_th),
                Paragraph("<b>Outliers</b>", style_th),
                Paragraph("<b>Outlier %</b>", style_th),
                Paragraph("<b>Lower Bound</b>", style_th),
                Paragraph("<b>Upper Bound</b>", style_th),
                Paragraph("<b>Severity</b>", style_th)
            ]
        ]
        for item in outlier.get("summary", []):
            outlier_table_data.append([
                Paragraph(str(item.get("column_name", "")), style_td_bold),
                Paragraph(f"{item.get('outlier_count', 0):,}", style_td),
                Paragraph(f"{item.get('percentage', 0):.2f}%", style_td),
                Paragraph(str(item.get("lower_bound", "")), style_td),
                Paragraph(str(item.get("upper_bound", "")), style_td),
                make_sev_p_cell(item.get("severity", "No Issue"))
            ])

        t_outlier = Table(outlier_table_data, colWidths=[140, 75, 75, 85, 85, 80])
        t_outlier.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), c_primary),
            ('GRID', (0,0), (-1,-1), 0.5, c_border),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_bg_subtle]),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(t_outlier)
        story.append(Spacer(1, 14))

        # --- Section 7: Strategic Recommendations & Action Matrix ---
        story.append(Paragraph("7. Strategic Recommendations & Remediation Plan", style_h1))
        recom_table_data = [
            [
                Paragraph("<b>Investigation Dimension</b>", style_th),
                Paragraph("<b>Severity</b>", style_th),
                Paragraph("<b>Business Risk / Impact</b>", style_th),
                Paragraph("<b>Actionable Recommendation</b>", style_th)
            ],
            [
                Paragraph("<b>Missing Values</b>", style_td_bold),
                make_sev_p_cell(missing["overall_severity"]),
                Paragraph(missing["business_impact"], style_td),
                Paragraph(missing["recommendation"], style_td_bold)
            ],
            [
                Paragraph("<b>Duplicate Records</b>", style_td_bold),
                make_sev_p_cell(dup["overall_severity"]),
                Paragraph(dup["business_impact"], style_td),
                Paragraph(dup["recommendation"], style_td_bold)
            ],
            [
                Paragraph("<b>Datatype Conformance</b>", style_td_bold),
                make_sev_p_cell(dtype["overall_severity"]),
                Paragraph(dtype["business_impact"], style_td),
                Paragraph(dtype["recommendation"], style_td_bold)
            ],
            [
                Paragraph("<b>Statistical Outliers</b>", style_td_bold),
                make_sev_p_cell(outlier["overall_severity"]),
                Paragraph(outlier["business_impact"], style_td),
                Paragraph(outlier["recommendation"], style_td_bold)
            ]
        ]
        t_recom = Table(recom_table_data, colWidths=[120, 70, 175, 175])
        t_recom.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), c_primary),
            ('GRID', (0,0), (-1,-1), 0.5, c_border),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_bg_subtle]),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(t_recom)

        # Build PDF with NumberedCanvas
        doc.build(story, canvasmaker=NumberedCanvas)
        buffer.seek(0)
        return buffer, None

    # ==========================================
    # EXCEL REPORT GENERATION (OpenPyXL)
    # ==========================================

    @classmethod
    def generate_excel(cls, filename: Optional[str] = None) -> Tuple[Optional[io.BytesIO], Optional[str]]:
        """
        Transforms cached DataLens report data into a structured, professionally styled Excel (.xlsx) workbook.
        """
        data, err = cls.get_all_reports_data(filename)
        if err or data is None:
            return None, err or "Failed to retrieve analysis data."

        wb = openpyxl.Workbook()
        # Remove default sheet
        wb.remove(wb.active)

        # Styling Tokens
        font_title = Font(name="Calibri", size=16, bold=True, color="0F172A")
        font_section = Font(name="Calibri", size=13, bold=True, color="1E3A8A")
        font_header = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
        font_bold = Font(name="Calibri", size=10, bold=True, color="0F172A")
        font_regular = Font(name="Calibri", size=10, color="0F172A")
        font_muted = Font(name="Calibri", size=9, italic=True, color="64748B")

        fill_header = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
        fill_sub_header = PatternFill(start_color="334155", end_color="334155", fill_type="solid")
        fill_zebra = PatternFill(start_color="F8FAFC", end_color="F8FAFC", fill_type="solid")
        fill_card = PatternFill(start_color="F1F5F9", end_color="F1F5F9", fill_type="solid")

        # Severity fills & fonts
        sev_styles = {
            "Critical": {"fill": PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid"), "font": Font(name="Calibri", size=10, bold=True, color="991B1B")},
            "High": {"fill": PatternFill(start_color="FFEDD5", end_color="FFEDD5", fill_type="solid"), "font": Font(name="Calibri", size=10, bold=True, color="9A3412")},
            "Medium": {"fill": PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid"), "font": Font(name="Calibri", size=10, bold=True, color="92400E")},
            "Low": {"fill": PatternFill(start_color="DBEAFE", end_color="DBEAFE", fill_type="solid"), "font": Font(name="Calibri", size=10, bold=True, color="1E40AF")},
            "No Issue": {"fill": PatternFill(start_color="DCFCE7", end_color="DCFCE7", fill_type="solid"), "font": Font(name="Calibri", size=10, bold=True, color="166534")},
        }

        thin_side = Side(border_style="thin", color="CBD5E1")
        border_all = Border(left=thin_side, right=thin_side, top=thin_side, bottom=thin_side)

        align_left = Alignment(horizontal="left", vertical="center")
        align_center = Alignment(horizontal="center", vertical="center")
        align_right = Alignment(horizontal="right", vertical="center")
        align_wrap = Alignment(horizontal="left", vertical="center", wrap_text=True)

        def auto_fit_cols(ws, min_width=12, max_width=45):
            ws.views.sheetView[0].showGridLines = True
            for col in ws.columns:
                col_letter = get_column_letter(col[0].column)
                max_len = 0
                for cell in col:
                    val = str(cell.value or "")
                    if cell.row == 1 or cell.row == 2:
                        continue
                    max_len = max(max_len, len(val))
                ws.column_dimensions[col_letter].width = max(min_width, min(max_len + 4, max_width))

        # ----------------------------------------------------
        # Sheet 1: Executive Summary
        # ----------------------------------------------------
        ws1 = wb.create_sheet(title="Executive Summary")
        ws1["A1"] = "DataLens Enterprise Data Quality Audit"
        ws1["A1"].font = font_title
        ws1["A2"] = f"Dataset: {data['filename']} | Generated: {data['generated_at']}"
        ws1["A2"].font = font_muted

        ws1["A4"] = "Executive Summary"
        ws1["A4"].font = font_section

        dash = data["dashboard"]["summary"]
        ws1["A5"] = "Health Score"
        ws1["B5"] = f"{dash['health_score']} / 100"
        ws1["A6"] = "Dataset Status"
        ws1["B6"] = dash["status"]
        ws1["A7"] = "Highest Priority Issue"
        ws1["B7"] = dash["highest_priority"]
        ws1["A8"] = "Total Quality Anomalies"
        ws1["B8"] = dash["total_issues"]
        ws1["A9"] = "Critical Severity Defects"
        ws1["B9"] = dash["critical_issues"]
        ws1["A10"] = "High Severity Defects"
        ws1["B10"] = dash["high_issues"]

        for r in range(5, 11):
            ws1[f"A{r}"].font = font_bold
            ws1[f"A{r}"].fill = fill_card
            ws1[f"A{r}"].border = border_all
            ws1[f"B{r}"].font = font_regular
            ws1[f"B{r}"].border = border_all
            ws1[f"B{r}"].alignment = align_left

        ws1["A12"] = "Deduction Score Breakdown"
        ws1["A12"].font = font_section
        ws1["A13"] = "Dimension"
        ws1["B13"] = "Deduction Points"
        ws1["A13"].font = font_header
        ws1["A13"].fill = fill_header
        ws1["B13"].font = font_header
        ws1["B13"].fill = fill_header

        curr_r = 14
        for k, v in data["dashboard"]["score_breakdown"].items():
            ws1[f"A{curr_r}"] = k
            ws1[f"B{curr_r}"] = f"-{v} pts"
            ws1[f"A{curr_r}"].border = border_all
            ws1[f"B{curr_r}"].border = border_all
            ws1[f"A{curr_r}"].font = font_regular
            ws1[f"B{curr_r}"].font = font_bold
            curr_r += 1

        curr_r += 1
        ws1[f"A{curr_r}"] = "Executive Insights"
        ws1[f"A{curr_r}"].font = font_section
        curr_r += 1
        for insight in data["dashboard"]["quick_insights"]:
            ws1[f"A{curr_r}"] = f"• {insight}"
            ws1[f"A{curr_r}"].font = font_regular
            curr_r += 1

        auto_fit_cols(ws1)

        # ----------------------------------------------------
        # Sheet 2: Dataset Overview
        # ----------------------------------------------------
        ws2 = wb.create_sheet(title="Dataset Overview")
        ws2["A1"] = "Dataset Overview"
        ws2["A1"].font = font_title
        ws2["A2"] = f"Structural health & volume metrics for {data['filename']}"
        ws2["A2"].font = font_muted

        overview = data["overview"]
        headers2 = ["Metric", "Value", "Description"]
        for c_idx, h in enumerate(headers2, 1):
            cell = ws2.cell(row=4, column=c_idx, value=h)
            cell.font = font_header
            cell.fill = fill_header
            cell.border = border_all

        overview_rows = [
            ("Dataset Name", overview["dataset_name"], "Active file audited"),
            ("Total Records (Rows)", overview["total_rows"], "Total number of row observations"),
            ("Total Attributes (Columns)", overview["total_columns"], "Total column features"),
            ("Numeric Columns", overview["numeric_columns"], "Continuous and discrete quantitative features"),
            ("Categorical Columns", overview["categorical_columns"], "Nominal and text classification features"),
            ("Missing Cell Values", overview["total_missing_values"], "Total null/empty values across all cells"),
            ("Duplicate Rows", overview["total_duplicate_records"], "Exact redundant record observations"),
            ("Memory Usage (MB)", f"{overview['memory_usage_mb']} MB", "Deep memory footprint in RAM"),
            ("Health Score", f"{overview['health_score']} / 100", "Composite quality score"),
            ("Health Status", overview["health_rating"], "Overall health tier")
        ]

        for r_idx, (m, v, desc) in enumerate(overview_rows, 5):
            c1 = ws2.cell(row=r_idx, column=1, value=m)
            c2 = ws2.cell(row=r_idx, column=2, value=v)
            c3 = ws2.cell(row=r_idx, column=3, value=desc)
            c1.font = font_bold
            c2.font = font_regular
            c3.font = font_muted
            c1.border = border_all
            c2.border = border_all
            c3.border = border_all
            if r_idx % 2 == 0:
                c1.fill = fill_zebra
                c2.fill = fill_zebra
                c3.fill = fill_zebra

        auto_fit_cols(ws2)

        # ----------------------------------------------------
        # Sheet 3: Missing Values
        # ----------------------------------------------------
        ws3 = wb.create_sheet(title="Missing Values")
        missing = data["missing"]
        ws3["A1"] = "Missing Values Investigation"
        ws3["A1"].font = font_title
        ws3["A2"] = f"Total Missing: {missing['total_missing_values']} | Missing Rows: {missing['percentage_missing_rows']}% | Severity: {missing['overall_severity']}"
        ws3["A2"].font = font_muted

        ws3["A4"] = "Business Impact"
        ws3["B4"] = missing["business_impact"]
        ws3["A5"] = "Action Recommendation"
        ws3["B5"] = missing["recommendation"]
        ws3["A4"].font = font_bold
        ws3["A5"].font = font_bold
        ws3["B4"].font = font_regular
        ws3["B5"].font = font_bold

        headers3 = ["Column Name", "Datatype", "Missing Count", "Missing %", "Severity"]
        for c_idx, h in enumerate(headers3, 1):
            cell = ws3.cell(row=7, column=c_idx, value=h)
            cell.font = font_header
            cell.fill = fill_header
            cell.border = border_all

        for r_idx, col in enumerate(missing.get("columns", []), 8):
            c1 = ws3.cell(row=r_idx, column=1, value=col.get("column_name"))
            c2 = ws3.cell(row=r_idx, column=2, value=col.get("datatype"))
            c3 = ws3.cell(row=r_idx, column=3, value=col.get("missing_count"))
            c4 = ws3.cell(row=r_idx, column=4, value=f"{col.get('missing_pct'):.2f}%")
            c5 = ws3.cell(row=r_idx, column=5, value=col.get("severity"))

            c1.font = font_bold
            c2.font = font_regular
            c3.font = font_regular
            c4.font = font_regular
            c1.border = border_all
            c2.border = border_all
            c3.border = border_all
            c4.border = border_all
            c5.border = border_all

            sev = col.get("severity", "No Issue")
            if sev in sev_styles:
                c5.fill = sev_styles[sev]["fill"]
                c5.font = sev_styles[sev]["font"]

            if r_idx % 2 == 0 and sev not in sev_styles:
                for c in (c1, c2, c3, c4):
                    c.fill = fill_zebra

        auto_fit_cols(ws3)

        # ----------------------------------------------------
        # Sheet 4: Duplicate Records
        # ----------------------------------------------------
        ws4 = wb.create_sheet(title="Duplicate Records")
        dup = data["duplicate"]
        ws4["A1"] = "Duplicate Records Investigation"
        ws4["A1"].font = font_title
        ws4["A2"] = f"Total Duplicates: {dup['total_duplicate_rows']} | Duplicate %: {dup['percentage_duplicates']}% | Severity: {dup['overall_severity']}"
        ws4["A2"].font = font_muted

        ws4["A4"] = "Business Impact"
        ws4["B4"] = dup["business_impact"]
        ws4["A5"] = "Action Recommendation"
        ws4["B5"] = dup["recommendation"]
        ws4["A4"].font = font_bold
        ws4["A5"].font = font_bold
        ws4["B4"].font = font_regular
        ws4["B5"].font = font_bold

        samples = dup.get("duplicate_samples", [])
        if samples:
            sample_keys = [k for k in samples[0].keys() if k != "duplicate_count"]
            headers4 = sample_keys + ["Duplicate Copies"]
            for c_idx, h in enumerate(headers4, 1):
                cell = ws4.cell(row=7, column=c_idx, value=h)
                cell.font = font_header
                cell.fill = fill_header
                cell.border = border_all

            for r_idx, row in enumerate(samples, 8):
                for c_idx, k in enumerate(sample_keys, 1):
                    cell = ws4.cell(row=r_idx, column=c_idx, value=str(row.get(k, "")))
                    cell.font = font_regular
                    cell.border = border_all
                    if r_idx % 2 == 0:
                        cell.fill = fill_zebra
                c_copies = ws4.cell(row=r_idx, column=len(sample_keys) + 1, value=row.get("duplicate_count", 2))
                c_copies.font = font_bold
                c_copies.border = border_all
                c_copies.alignment = align_center
        else:
            ws4["A7"] = "No duplicate records detected in the active dataset."
            ws4["A7"].font = font_regular

        auto_fit_cols(ws4)

        # ----------------------------------------------------
        # Sheet 5: Datatype Validation
        # ----------------------------------------------------
        ws5 = wb.create_sheet(title="Datatype Validation")
        dtype = data["datatype"]
        ws5["A1"] = "Datatype Schema Conformance"
        ws5["A1"].font = font_title
        ws5["A2"] = f"Total Invalid Values: {dtype['total_invalid_types']} | Columns Analyzed: {dtype['columns_analyzed']} | Severity: {dtype['overall_severity']}"
        ws5["A2"].font = font_muted

        ws5["A4"] = "Business Impact"
        ws5["B4"] = dtype["business_impact"]
        ws5["A5"] = "Action Recommendation"
        ws5["B5"] = dtype["recommendation"]
        ws5["A4"].font = font_bold
        ws5["A5"].font = font_bold
        ws5["B4"].font = font_regular
        ws5["B5"].font = font_bold

        headers5 = ["Column Name", "Detected Type", "Expected Type", "Invalid Count", "Severity", "Description"]
        for c_idx, h in enumerate(headers5, 1):
            cell = ws5.cell(row=7, column=c_idx, value=h)
            cell.font = font_header
            cell.fill = fill_header
            cell.border = border_all

        for r_idx, issue in enumerate(dtype.get("issues", []), 8):
            c1 = ws5.cell(row=r_idx, column=1, value=issue.get("column_name"))
            c2 = ws5.cell(row=r_idx, column=2, value=issue.get("detected_type"))
            c3 = ws5.cell(row=r_idx, column=3, value=issue.get("expected_type"))
            c4 = ws5.cell(row=r_idx, column=4, value=issue.get("invalid_count"))
            c5 = ws5.cell(row=r_idx, column=5, value=issue.get("severity"))
            c6 = ws5.cell(row=r_idx, column=6, value=issue.get("issue_description"))

            c1.font = font_bold
            c2.font = font_regular
            c3.font = font_regular
            c4.font = font_regular
            c6.font = font_muted

            for c in (c1, c2, c3, c4, c5, c6):
                c.border = border_all

            sev = issue.get("severity", "No Issue")
            if sev in sev_styles:
                c5.fill = sev_styles[sev]["fill"]
                c5.font = sev_styles[sev]["font"]

            if r_idx % 2 == 0:
                for c in (c1, c2, c3, c4, c6):
                    c.fill = fill_zebra

        auto_fit_cols(ws5)

        # ----------------------------------------------------
        # Sheet 6: Outlier Detection
        # ----------------------------------------------------
        ws6 = wb.create_sheet(title="Outlier Detection")
        outlier = data["outlier"]
        ws6["A1"] = "Statistical Outlier Detection"
        ws6["A1"].font = font_title
        ws6["A2"] = f"Total Outliers: {outlier['total_outliers']} | Features Analyzed: {outlier['columns_analyzed']} | Severity: {outlier['overall_severity']}"
        ws6["A2"].font = font_muted

        ws6["A4"] = "Business Impact"
        ws6["B4"] = outlier["business_impact"]
        ws6["A5"] = "Action Recommendation"
        ws6["B5"] = outlier["recommendation"]
        ws6["A4"].font = font_bold
        ws6["A5"].font = font_bold
        ws6["B4"].font = font_regular
        ws6["B5"].font = font_bold

        headers6 = ["Column Name", "Outlier Count", "Outlier %", "Lower Bound", "Upper Bound", "Min Value", "Max Value", "Severity"]
        for c_idx, h in enumerate(headers6, 1):
            cell = ws6.cell(row=7, column=c_idx, value=h)
            cell.font = font_header
            cell.fill = fill_header
            cell.border = border_all

        for r_idx, item in enumerate(outlier.get("summary", []), 8):
            c1 = ws6.cell(row=r_idx, column=1, value=item.get("column_name"))
            c2 = ws6.cell(row=r_idx, column=2, value=item.get("outlier_count"))
            c3 = ws6.cell(row=r_idx, column=3, value=f"{item.get('percentage'):.2f}%")
            c4 = ws6.cell(row=r_idx, column=4, value=item.get("lower_bound"))
            c5 = ws6.cell(row=r_idx, column=5, value=item.get("upper_bound"))
            c6 = ws6.cell(row=r_idx, column=6, value=item.get("min_val"))
            c7 = ws6.cell(row=r_idx, column=7, value=item.get("max_val"))
            c8 = ws6.cell(row=r_idx, column=8, value=item.get("severity"))

            c1.font = font_bold
            c2.font = font_regular
            c3.font = font_regular
            c4.font = font_regular
            c5.font = font_regular
            c6.font = font_regular
            c7.font = font_regular

            for c in (c1, c2, c3, c4, c5, c6, c7, c8):
                c.border = border_all

            sev = item.get("severity", "No Issue")
            if sev in sev_styles:
                c8.fill = sev_styles[sev]["fill"]
                c8.font = sev_styles[sev]["font"]

            if r_idx % 2 == 0:
                for c in (c1, c2, c3, c4, c5, c6, c7):
                    c.fill = fill_zebra

        auto_fit_cols(ws6)

        # ----------------------------------------------------
        # Sheet 7: Recommendations
        # ----------------------------------------------------
        ws7 = wb.create_sheet(title="Recommendations")
        ws7["A1"] = "Consolidated Quality Recommendations"
        ws7["A1"].font = font_title
        ws7["A2"] = f"Remediation Action Matrix for {data['filename']}"
        ws7["A2"].font = font_muted

        headers7 = ["Investigation Dimension", "Highest Severity", "Business Risk / Impact", "Prescribed Action"]
        for c_idx, h in enumerate(headers7, 1):
            cell = ws7.cell(row=4, column=c_idx, value=h)
            cell.font = font_header
            cell.fill = fill_header
            cell.border = border_all

        recom_rows = [
            ("Missing Values", missing["overall_severity"], missing["business_impact"], missing["recommendation"]),
            ("Duplicate Records", dup["overall_severity"], dup["business_impact"], dup["recommendation"]),
            ("Datatype Conformance", dtype["overall_severity"], dtype["business_impact"], dtype["recommendation"]),
            ("Statistical Outliers", outlier["overall_severity"], outlier["business_impact"], outlier["recommendation"]),
        ]

        for r_idx, (dim, sev, impact, rec) in enumerate(recom_rows, 5):
            c1 = ws7.cell(row=r_idx, column=1, value=dim)
            c2 = ws7.cell(row=r_idx, column=2, value=sev)
            c3 = ws7.cell(row=r_idx, column=3, value=impact)
            c4 = ws7.cell(row=r_idx, column=4, value=rec)

            c1.font = font_bold
            c3.font = font_regular
            c4.font = font_bold

            for c in (c1, c2, c3, c4):
                c.border = border_all

            if sev in sev_styles:
                c2.fill = sev_styles[sev]["fill"]
                c2.font = sev_styles[sev]["font"]

            if r_idx % 2 == 0:
                c1.fill = fill_zebra
                c3.fill = fill_zebra

        auto_fit_cols(ws7)

        # Save workbook to buffer
        buffer = io.BytesIO()
        wb.save(buffer)
        buffer.seek(0)
        return buffer, None
